name: .NET
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: dotnet clean
      run: dotnet clean
      working-directory: Paysafe
    - name: dotnet build & pack
      shell: pwsh
      working-directory: Paysafe
      run: |
          $branch = @($env:GITHUB_REF -split "/")[-1]
          if ($branch -eq "master") {
            dotnet build --configuration Release
            dotnet pack --no-build --configuration Release -o out
          } else {
            $runNumber = $env:GITHUB_RUN_NUMBER
            dotnet build --configuration Release --version-suffix "$branch$runNumber"
            dotnet pack --no-build --configuration Release --version-suffix "$branch$runNumber" -o out
          }
    - name: publish to nuget
      run: dotnet nuget push ./Paysafe/out/Paysafe.NetStandard.*.nupkg -k ${{ secrets.Nuget_tristan }} -s https://api.nuget.org/v3/index.json